name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Hugging Face
      run: |
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}
        huggingface-cli repo create YT_Transcribe --organization your_org_name --token ${{ secrets.HF_TOKEN }}
        git push https://huggingface.co/your_org_name/YT_Transcribe
